unfoldingWord/gateway-translate

- pages/_app.js
- pages/index.js
- src/common/BooksOfTheBible.js
- src/common/constants.js
- src/components/Header.js
- src/components/ScriptureWorkspace.js
- src/components/ScriptureWorkspaceCard.js
- src/components/SelectBookPopup.js
- src/context/AppContext.js
> Feature cn 1 select book popup

- src/components/ScriptureWorkspace.js
- src/components/ScriptureWorkspaceCard.js
> add type to card title

- src/components/ScriptureWorkspace.js
- src/components/ScriptureWorkspaceCard.js
> fix window close, id was wrong

- src/utils/data-helpers/middleware-handler.js
- Some bad code was breaking the build process. Commented it out since it was unused.
> Fix netlify build

- src/components/ScriptureWorkspaceCard.js
- src/context/AppContext.js
> Fixes for local storage and wait indication

- package.json
- src/components/Header.js
- src/components/ScriptureWorkspace.js
- src/components/ScriptureWorkspaceCard.js
- src/context/AppContext.js
- src/utils/createUserBranch.js
- src/utils/existsUserBranch.js
- src/utils/perf2usfm.js
- src/utils/saveToUserBranch.js
- src/utils/usfm2perf.js
- yarn.lock
> Feature cn 11 dcs branch management

- package.json
- src/components/ScriptureWorkspaceCard.js
- src/utils/perf2usfm.js
- src/utils/saveToUserBranch.js
- yarn.lock
> Feature cn 22 save to user branch

- package.json
- src/components/ScriptureWorkspaceCard.js
- src/context/AppContext.js
- yarn.lock
Change epitelete-perf-html -> epitelete-html.
Rename props and vars.
> Update uw-editor and rename epitelete-html

- src/components/ScriptureWorkspaceCard.js
- src/context/AppContext.js
- src/utils/fetchFromUserBranch.js
- src/utils/saveToUserBranch.js
- src/utils/userbranch.js
- src/utils/usfm2perf.js
> fix branch on read bug and other fails

- package.json
- src/components/Header.js
- src/context/AppContext.js
- src/utils/randomLetters.js
> Fix book id doc set

- package.json
- src/common/BooksOfTheBible.js
- src/components/Header.js
- src/components/ScriptureWorkspaceCard.js
- src/components/SelectBookPopup.js
- src/context/AppContext.js
- src/utils/base64Decode.js
- yarn.lock
#63 
For the curious it looks like this:
> Add support for any repo, url or file upload

- package.json
Also note that the user can easily click the pencil icon and save changes to local storage.
> re-fix. but upload may still need work

- src/components/FeedbackCard.js
> Fixed by adding some tailwind css

- src/components/Header.js
> Shows a snackbar notice for 6 seconds

- src/components/Header.js
> Sticky App Bar

- src/components/SelectBookPopup.js
> Clear url on submit

- src/components/SelectBookPopup.js
> Fix for URL field focus in the SelectBookPopup

- src/components/ScriptureWorkspaceCard.js
- yarn.lock
- Solves issue: [Width of text is limited unnecessarily](https://github.com/unfoldingWord/uw-editor/issues/9)
> remove max width of usfmeditor card

- package.json
> bump version of uw-editor and this

- package.json
- yarn.lock
> upgrade to uw-editor@v0.1.21

- .gitignore
- package.json
- src/components/BibleReference.jsx
- src/components/Header.js
- src/components/ScriptureWorkspaceCard.js
- src/styles/HtmlSequenceEditor.css
- yarn.lock
https://github.com/unfoldingWord/gateway-translate/issues/65
-  use accompanying PR from UW-editor
-  open one or more of the same book in different versions
- Change chapter or verse at top
> Add reference navigation 

- src/components/ScriptureWorkspace.js
> WIP - fixed... more testing

- package.json
- src/components/Header.js
- src/components/ScriptureWorkspace.js
- src/components/ScriptureWorkspaceCard.js
- src/context/AppContext.js
- yarn.lock
> incorporate new uw-editor

- package.json
- yarn.lock
> increased memory limit

- package.json
- src/utils/userbranch.js
> branch name change

- package.json
- src/components/Header.js
> fix for issue 172
